[[build_tools]]
name = "cmake"
version = "3.30.5"
url = "https://github.com/Kitware/CMake/releases/download/v3.30.5/cmake-3.30.5-linux-x86_64.tar.gz"
archive = "cmake-3.30.5-linux-x86_64.tar.gz"
paths = ["cmake-3.30.5-linux-x86_64/bin"]

[[build_tools]]
name = "ninja"
version = "v1.12.1"
url = "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux.zip"
archive = "ninja-linux-x86_64-v1.12.1.zip"
paths = ["ninja-linux-x86_64-v1.12.1"]

[[build_tools]]
name = "bazel"
version = "7.4.1"
url = "https://github.com/bazelbuild/bazel/releases/download/7.4.1/bazel-7.4.1-linux-x86_64"
archive = "bazel"

[[build_tools]]
name = "ccache"
version = "4.12.1"
url = "https://github.com/ccache/ccache/releases/download/v4.12.1/ccache-4.12.1-linux-x86_64.tar.xz"
archive = "ccache-4.12.1-linux-x86_64.tar.xz"
paths = ["ccache-4.12.1-linux-x86_64"]
