# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ubuntu-amd64-gcc-11.5

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Install build-essential
      run: sudo apt update && sudo apt install -y build-essential

    - name: Build
      run: go build -v ./...

    - name: Test(GCC)
      env:
        GO_TEST_TIMEOUT: 1h
        TEST_GCC: ON
      run: |
        go test -v ./depcheck/... -timeout $GO_TEST_TIMEOUT
        go test -v ./configs/...  -timeout $GO_TEST_TIMEOUT
        go test -v ./pkgs/git/... -timeout $GO_TEST_TIMEOUT
        go test -v ./cmds/... -timeout $GO_TEST_TIMEOUT
