# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: windows-x86_64-msvc-nobuild

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_test:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4

      - name: Install tar
        run: choco install archiver 7zip -y

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.50.35717
          arch: x64

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"

      - name: Build Celer
        run: go build -v ./...

      - name: Test
        run: go test -tags=test_msvc -v ./cmds/ -run "TestInstall_x86_64_MSVC_Nobuild" -timeout 1h
