# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: windows-amd64-msvc-14.44

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_test:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: 14.44.35207
        arch: x64

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'
    
    - name: Build
      run: go build -v ./...

    - name: Test(GCC)
      env:
        GO_TEST_TIMEOUT: 1h
        GO_TEST_MSVC: ON
      run: |
        go test -v ./depcheck/... -timeout %GO_TEST_TIMEOUT%
        go test -v ./configs/...  -timeout %GO_TEST_TIMEOUT%
        go test -v ./pkgs/git/... -timeout %GO_TEST_TIMEOUT%
        go test -v ./cmds/... -timeout %GO_TEST_TIMEOUT%