# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: windows-x86_64-clang-cl-prebuilt

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_test:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Install tar
        run: choco install archiver -y

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.44.35207
          arch: x64

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"

      - name: Build Celer
        run: go build -v ./...

      - name: Test(x86_64_Clang_Prebuilt)
        run: go test -tags=test_clang_cl -v ./cmds/ -run "TestInstall_x86_64_Clang_CL_Prebuilt" -timeout 1h
