# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: windows-amd64-clang-cl-14.44

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_test:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Install tar
        run: choco install archiver -y

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.44.35207
          arch: x64

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"

      - name: Free disk space
        shell: bash
        run: |
          echo "Disk space before cleanup:"
          df -h
          
          rm -rf /c/hostedtoolcache/windows/Ruby
          rm -rf /c/hostedtoolcache/windows/Python
          rm -rf "C:\\ProgramData\\chocolatey"
          
          echo "Disk space after cleanup:"
          df -h

      - name: Build
        run: go build -v ./...

      - name: Test(AMD64_Clang-CL)
        run: |
          go test -v ./depcheck/... -timeout 1h
          go test -v ./configs/...  -timeout 1h
          go test -v ./pkgs/git/... -timeout 1h
          go test -tags=test_clang_cl -v ./cmds/... -timeout 1h
